DROP DATABASE IF EXISTS stabilimenti;
CREATE DATABASE stabilimenti;
USE stabilimenti;

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome varchar(64) NOT NULL
);

CREATE TABLE beaches (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(64) NOT NULL
);

CREATE TABLE admins (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(64) NOT NULL
)